export const DEFAULT_LANGUAGE = 'az';

export const SUPPORTED_LANGUAGES = [
  { code: 'az', label: 'Azərbaycanca' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'ru', label: 'Русский' },
];

const LANGUAGE_CODES = new Set(SUPPORTED_LANGUAGES.map((language) => language.code));

const translations = {
  az: {
    common: {
      appName: 'Language Learning App',
      language: 'Dil',
      home: 'Ana səhifə',
      lessons: 'Dərslər',
      practice: 'Təcrübə',
      progress: 'İrəliləyiş',
      available: 'Mövcuddur',
      privacyPolicy: 'Məxfilik siyasəti',
      contactSupport: 'Dəstəyə yaz',
      allRightsReserved: 'Bütün hüquqlar qorunur.',
      live: 'Canlı',
      connected: 'Qoşulub',
      enabled: 'Aktiv',
      locked: 'Bağlı',
      unavailable: 'Mövcud deyil',
      free: 'Pulsuz',
      loaderUnavailable: 'Bu render axınında canlı yükləyici məlumatı müvəqqəti əlçatan deyil.',
      wordFallback: 'Söz {id}',
      languageSaved: 'Dil seçimi yadda saxlanıldı.',
    },
    shell: {
      title: 'Azerbaycan dilini sistemli şəkildə öyrən',
      subtitle: 'Dərslər, təcrübə və irəliləyiş səhifələrini seçdiyiniz dildə idarə edin.',
      switcherLabel: 'İnterfeys dili',
    },
    errors: {
      appErrorDetected: 'Tətbiq xətası aşkarlandı',
      appErrorDescription: 'Tətbiqdən istifadə zamanı xəta baş verdi.',
      tryToFix: 'Düzəltməyə çalış',
      showLogs: 'Loqları göstər',
      copyError: 'Xətanı kopyala',
    },
    home: {
      metaTitle: 'Onlayn Azərbaycan dili öyrənin',
      metaDescription: 'CEFR marşrutları, AI təcrübəsi və çevik planlarla Azərbaycan dili platforması.',
      badge: 'Azərbaycan dili öyrənmə platforması',
      title: 'Boş marşrut yox, həqiqi məhsul hissi verən yol ilə Azərbaycan dili öyrənin.',
      subtitle: 'Ana səhifə artıq repodakı mövcud dərs, qiymət və alış API-lərindən oxuyur ki, öyrənən təcrübəsi real məlumatları göstərsin.',
      browseLessons: 'Dərslərə bax',
      startPractice: 'Təcrübəyə başla',
      viewProgress: 'İrəliləyişi aç',
      lessonLibrary: 'Dərs kitabxanası',
      lessonLibrarySummary: '{bandCount} CEFR zolağı və {lessonCount} dərs qeydi /api/lessons üzərindən əlçatandır.',
      livePricing: 'Canlı qiymətlər',
      livePricingSummary: '{planCount} abunə səviyyəsi /api/pricing?action=plans üzərindən yüklənir.',
      practiceSurfaces: 'Təcrübə səthləri',
      practiceSurfacesSummary: 'Spaced repetition və irəliləyiş artıq mövcud API-lərlə ayrıca öyrənən marşrutlarına malikdir.',
      addOnCatalog: 'Əlavələr kataloqu',
      addOnCatalogSummary: '{categoryCount} alış kateqoriyası /api/purchases?action=available üzərindən yüklənir.',
      learningSnapshot: 'Öyrənmə xülasəsi',
      weeklyRhythm: 'Həftəlik ritm',
      lessonApiStatus: 'Dərs API statusu',
      needsDatabase: 'Verilənlər bazası lazımdır',
      lessonStatusSummary: 'Dərs məlumatı öyrənən səhifələri və ana səhifə xülasələri üçün mövcuddur.',
      lessonsLabel: 'Dərslər',
      plansLabel: 'Planlar',
      catalogsLabel: 'Kataloqlar',
      lessonsSectionTitle: 'API-dən gələn real dərs zolaqları',
      lessonsSectionDescription: 'Dərs səhifələri indi /api/lessons ilə işləyir. Verilənlər bazası qurulmayıbsa, interfeys bunu birbaşa göstərir.',
      unavailableLevel: 'Mövcud deyil',
      lessonCount: '{count} dərs',
      configureDatabase: 'Öyrənən məzmun qeydlərini yükləmək üçün DATABASE_URL konfiqurasiya edin.',
      groupedByLevel: 'Canlı dərs endpointindən çəkilib və səviyyəyə görə qruplaşdırılıb.',
      plansSectionTitle: 'Fərqli öyrənmə dərinliyi üçün planlar',
      curriculumSummary: '{range} kurikulum, {exercises} tapşırıq, {sessions} canlı müəllim sessiyası.',
      pricingDetailsLoaded: 'Qiymət detalları qiymət API-sindən yüklənib.',
      pricingUnavailableTitle: 'Qiymət planları mövcud deyil',
      pricingUnavailableDescription: 'Ana səhifə yerli qiymət kataloqunu qura bilmədi.',
      catalogSectionTitle: 'Purchases API-dən real əlavələr',
      catalogSectionDescription: 'Satın alınan əlavə məhsullar mövcud API cavablarından göstərilir.',
      catalogUnavailableTitle: 'Kataloq məlumatı mövcud deyil',
      catalogUnavailableDescription: 'Ana səhifə yerli alış kataloqunu qura bilmədi.',
    },
    lessonsPage: {
      metaTitle: 'Dərslər',
      metaDescription: 'Azərbaycan dili məzmun API-sindən dərs qeydlərinə baxın.',
      eyebrow: 'Dərslər',
      title: 'Real dərs məzmunu',
      subtitle: 'Bu marşrut birbaşa /api/lessons-dan oxuyur və nəticələri CEFR zolaqlarına görə qruplaşdırır.',
      dataUnavailable: 'Dərs məlumatı mövcud deyil',
      noLessonRecords: 'Hələ dərs qeydi yoxdur',
      noLessonRecordsDescription: 'Marşrut real dərs API-sinə bağlıdır, amma hazırda heç bir dərs sətri qaytarmır.',
      navigation: 'Naviqasiya',
      practiceQueue: 'Təcrübə növbəsi',
      progressOverview: 'İrəliləyiş görünüşü',
      accessTiers: 'Giriş səviyyələri',
      levelLabel: 'Səviyyə {level}',
      minutesLabel: '{minutes} dəq',
      curriculumAccess: '{range} kurikuluma giriş',
      curriculumVaries: 'Kurikulum girişi plana görə dəyişir.',
    },
    practicePage: {
      metaTitle: 'Təcrübə',
      metaDescription: 'Canlı öyrənən API-ləri ilə spaced repetition elementlərini təkrarlayın.',
      eyebrow: 'Təcrübə',
      title: 'Spaced repetition növbəsi',
      subtitle: 'Bu səhifə /api/user və /api/spaced-repetition istifadə edir və demo öyrənən qeydi {email} ünvanındadır.',
      updateFailed: 'Təkrar elementi yenilənmədi.',
      dataUnavailable: 'Təcrübə məlumatı mövcud deyil',
      learner: 'Öyrənən',
      dueNow: 'İndi vaxtıdır',
      status: 'Status',
      ready: 'Hazırdır',
      cleared: 'Təmizlənib',
      reviewDue: 'Təkrar vaxtı çatıb',
      translationUnavailable: 'Tərcümə mövcud deyil',
      interval: 'Interval {days}g',
      repetitions: 'Təkrar sayı {count}',
      ease: 'Asanlıq {value}',
      again: 'Yenə',
      hard: 'Çətin',
      good: 'Yaxşı',
      easy: 'Asan',
      noItemsDue: 'Hazırda təcrübə elementi yoxdur',
      noItemsDueDescription: 'Canlı spaced repetition endpointi vaxtı çatmış element qaytarmadı. Bu, növbənin boş olması və ya öyrənən datasetinin hələ mövcud olmaması demək ola bilər.',
      aiTutorPacks: 'AI müəllim kredit paketləri',
      goToProgress: 'İrəliləyişə keç',
      packLabel: 'Paket {key}',
    },
    progressPage: {
      metaTitle: 'İrəliləyiş',
      metaDescription: 'Öyrənən profilini, hüquqları və yüksəltmə tövsiyələrini izləyin.',
      eyebrow: 'İrəliləyiş',
      title: 'Öyrənən profili və giriş hüquqları',
      subtitle: 'Bu marşrut /api/user, /api/subscriptions və qiymət tövsiyə endpointlərindən oxuyur.',
      dataUnavailable: 'İrəliləyiş məlumatının bir hissəsi mövcud deyil',
      cefrLevel: 'CEFR səviyyəsi',
      xp: 'XP',
      streak: 'Seriya',
      plan: 'Plan',
      currentEntitlements: 'Cari hüquqlar',
      accessLevel: 'Giriş səviyyəsi',
      offlineMode: 'Offline rejim',
      aiPersonalization: 'AI fərdiləşdirmə',
      speechRecognition: 'Nitqin tanınması',
      storage: 'Yaddaş',
      aiCredits: 'AI kreditləri',
      upgradeRecommendations: 'Yüksəltmə tövsiyələri',
      practiceQueue: 'Təcrübə növbəsi',
      upgradeTo: '{plan} planına keçin',
      noRecommendations: 'Canlı tövsiyə qeydləri qaytarılmadı. Bu adətən öyrənən profilinin çatışmadığını və ya hələ kifayət qədər istifadə məlumatı olmadığını göstərir.',
      availablePlans: 'Mövcud planlar',
      openLessons: 'Dərsləri aç',
      curriculumAccess: '{range} kurikuluma giriş',
      livePlanMetadata: 'Canlı plan məlumatı qiymət API-sindən gəlir.',
      storageAmount: '{amount} MB',
    },
    notFound: {
      back: 'Geri',
      title: 'Bu səhifə hələ mövcud deyil.',
      subtitle: '"/{path}" layihənizin bir hissəsi deyil. Amma seçimləriniz var.',
      buildFromScratch: 'Sıfırdan qurun',
      createPageDescription: '"/{path}" ünvanında yeni səhifə yaradın',
      createPage: 'Səhifə yarat',
      routesHint: 'Layihənizin bütün marşrutları burada göstərilir ↓',
      pages: 'SƏHİFƏLƏR',
      homepage: 'Ana səhifə',
    },
  },
  tr: {
    common: {
      appName: 'Language Learning App',
      language: 'Dil',
      home: 'Ana sayfa',
      lessons: 'Dersler',
      practice: 'Pratik',
      progress: 'İlerleme',
      available: 'Mevcut',
      privacyPolicy: 'Gizlilik politikası',
      contactSupport: 'Destek ile iletişim',
      allRightsReserved: 'Tüm hakları saklıdır.',
      live: 'Canlı',
      connected: 'Bağlı',
      enabled: 'Açık',
      locked: 'Kilitli',
      unavailable: 'Yok',
      free: 'Ücretsiz',
      loaderUnavailable: 'Canlı yükleyici verisi bu render akışında geçici olarak kullanılamıyor.',
      wordFallback: 'Kelime {id}',
      languageSaved: 'Dil tercihi kaydedildi.',
    },
    shell: {
      title: 'Azerbaycan Türkçesini düzenli bir akışla öğrenin',
      subtitle: 'Ders, pratik ve ilerleme sayfalarını seçtiğiniz arayüz diliyle yönetin.',
      switcherLabel: 'Arayüz dili',
    },
    errors: {
      appErrorDetected: 'Uygulama hatası algılandı',
      appErrorDescription: 'Uygulamayı kullanırken bir hata oluştu.',
      tryToFix: 'Düzeltmeyi dene',
      showLogs: 'Logları göster',
      copyError: 'Hatayı kopyala',
    },
    home: {
      metaTitle: 'Online Azerbaycan dili öğrenin',
      metaDescription: 'CEFR yolları, yapay zeka pratiği ve esnek planlarla Azerbaycan dili platformu.',
      badge: 'Azerbaycan dili öğrenme platformu',
      title: 'Boş bir rota yerine gerçek bir ürün hissi veren bir akışla Azerbaycan dili öğrenin.',
      subtitle: 'Ana sayfa artık depodaki mevcut ders, fiyatlandırma ve satın alma API’lerinden okuyor; böylece öğrenci deneyimi gerçek veri yüzeylerini yansıtıyor.',
      browseLessons: 'Derslere göz at',
      startPractice: 'Pratiğe başla',
      viewProgress: 'İlerlemeyi gör',
      lessonLibrary: 'Ders kütüphanesi',
      lessonLibrarySummary: '{bandCount} CEFR bandı ve {lessonCount} ders kaydı /api/lessons üzerinden kullanılabilir.',
      livePricing: 'Canlı fiyatlandırma',
      livePricingSummary: '{planCount} abonelik katmanı /api/pricing?action=plans üzerinden yükleniyor.',
      practiceSurfaces: 'Pratik yüzeyleri',
      practiceSurfacesSummary: 'Aralıklı tekrar ve ilerleme artık mevcut API’leri kullanan ayrı öğrenci rotalarına sahip.',
      addOnCatalog: 'Ek ürün kataloğu',
      addOnCatalogSummary: '{categoryCount} satın alma kategorisi /api/purchases?action=available üzerinden yükleniyor.',
      learningSnapshot: 'Öğrenme özeti',
      weeklyRhythm: 'Haftalık ritim',
      lessonApiStatus: 'Ders API durumu',
      needsDatabase: 'Veritabanı gerekli',
      lessonStatusSummary: 'Ders verileri öğrenci sayfaları ve ana sayfa özetleri için hazır.',
      lessonsLabel: 'Dersler',
      plansLabel: 'Planlar',
      catalogsLabel: 'Kataloglar',
      lessonsSectionTitle: 'API’den gelen gerçek ders bantları',
      lessonsSectionDescription: 'Ders sayfaları artık /api/lessons ile çalışıyor. Veritabanı yapılandırılmadıysa arayüz bunu doğrudan gösterir.',
      unavailableLevel: 'Yok',
      lessonCount: '{count} ders',
      configureDatabase: 'Öğrenci içerik kayıtlarını yüklemek için DATABASE_URL yapılandırın.',
      groupedByLevel: 'Canlı ders uç noktasından çekildi ve seviyeye göre gruplandı.',
      plansSectionTitle: 'Farklı çalışma derinlikleri için tasarlanmış fiyatlandırma',
      curriculumSummary: '{range} müfredat, {exercises} alıştırma, {sessions} canlı eğitmen oturumu.',
      pricingDetailsLoaded: 'Fiyat ayrıntıları fiyatlandırma API’sinden yüklendi.',
      pricingUnavailableTitle: 'Fiyat planları kullanılamıyor',
      pricingUnavailableDescription: 'Ana sayfa yerel fiyat kataloğunu oluşturamadı.',
      catalogSectionTitle: 'Purchases API’den gerçek ek ürünler',
      catalogSectionDescription: 'Satın alınabilir ek ürünler mevcut API yanıtlarından gösterilir.',
      catalogUnavailableTitle: 'Katalog verisi kullanılamıyor',
      catalogUnavailableDescription: 'Ana sayfa yerel satın alma kataloğunu oluşturamadı.',
    },
    lessonsPage: {
      metaTitle: 'Dersler',
      metaDescription: 'Azerbaycan dili içerik API’sinden ders kayıtlarını inceleyin.',
      eyebrow: 'Dersler',
      title: 'Gerçek ders içeriği',
      subtitle: 'Bu rota doğrudan /api/lessons verisini okur ve sonuçları CEFR bandına göre gruplar.',
      dataUnavailable: 'Ders verisi kullanılamıyor',
      noLessonRecords: 'Henüz ders kaydı yok',
      noLessonRecordsDescription: 'Rota gerçek ders API’sine bağlı, ancak şu anda hiç ders satırı dönmüyor.',
      navigation: 'Gezinme',
      practiceQueue: 'Pratik kuyruğu',
      progressOverview: 'İlerleme görünümü',
      accessTiers: 'Erişim katmanları',
      levelLabel: 'Seviye {level}',
      minutesLabel: '{minutes} dk',
      curriculumAccess: '{range} müfredata erişim',
      curriculumVaries: 'Müfredat erişimi plana göre değişir.',
    },
    practicePage: {
      metaTitle: 'Pratik',
      metaDescription: 'Canlı öğrenci API’leri ile aralıklı tekrar öğelerini gözden geçirin.',
      eyebrow: 'Pratik',
      title: 'Aralıklı tekrar kuyruğu',
      subtitle: 'Bu sayfa /api/user ve /api/spaced-repetition kullanır ve demo öğrenci kaydı {email} adresindedir.',
      updateFailed: 'Tekrar öğesi güncellenemedi.',
      dataUnavailable: 'Pratik verisi kullanılamıyor',
      learner: 'Öğrenci',
      dueNow: 'Şimdi zamanı',
      status: 'Durum',
      ready: 'Hazır',
      cleared: 'Temiz',
      reviewDue: 'Tekrar zamanı',
      translationUnavailable: 'Çeviri yok',
      interval: 'Aralık {days}g',
      repetitions: 'Tekrar {count}',
      ease: 'Kolaylık {value}',
      again: 'Tekrar',
      hard: 'Zor',
      good: 'İyi',
      easy: 'Kolay',
      noItemsDue: 'Şu anda pratik öğesi yok',
      noItemsDueDescription: 'Canlı aralıklı tekrar uç noktası zamanı gelen öğe döndürmedi. Bu, kuyruğun boş olduğu ya da öğrenci verisinin henüz hazır olmadığı anlamına gelebilir.',
      aiTutorPacks: 'Yapay zeka eğitmen kredi paketleri',
      goToProgress: 'İlerlemeye git',
      packLabel: 'Paket {key}',
    },
    progressPage: {
      metaTitle: 'İlerleme',
      metaDescription: 'Öğrenci profilini, hakları ve yükseltme önerilerini takip edin.',
      eyebrow: 'İlerleme',
      title: 'Öğrenci profili ve erişim',
      subtitle: 'Bu rota /api/user, /api/subscriptions ve fiyat öneri uç noktalarından veri okur.',
      dataUnavailable: 'İlerleme verisinin bir kısmı kullanılamıyor',
      cefrLevel: 'CEFR seviyesi',
      xp: 'XP',
      streak: 'Seri',
      plan: 'Plan',
      currentEntitlements: 'Geçerli haklar',
      accessLevel: 'Erişim seviyesi',
      offlineMode: 'Çevrimdışı mod',
      aiPersonalization: 'Yapay zeka kişiselleştirme',
      speechRecognition: 'Konuşma tanıma',
      storage: 'Depolama',
      aiCredits: 'AI kredileri',
      upgradeRecommendations: 'Yükseltme önerileri',
      practiceQueue: 'Pratik kuyruğu',
      upgradeTo: '{plan} planına yükselt',
      noRecommendations: 'Canlı öneri kaydı dönmedi. Bu genelde öğrenci profilinin eksik olduğu ya da henüz yeterli kullanım verisi bulunmadığı anlamına gelir.',
      availablePlans: 'Mevcut planlar',
      openLessons: 'Dersleri aç',
      curriculumAccess: '{range} müfredat erişimi',
      livePlanMetadata: 'Canlı plan verisi fiyatlandırma API’sinden geliyor.',
      storageAmount: '{amount} MB',
    },
    notFound: {
      back: 'Geri',
      title: 'Bu sayfa henüz mevcut değil.',
      subtitle: '"/{path}" projenizin parçası değil. Ama seçenekleriniz var.',
      buildFromScratch: 'Sıfırdan oluştur',
      createPageDescription: '"/{path}" adresinde yeni bir sayfa oluştur',
      createPage: 'Sayfa oluştur',
      routesHint: 'Projenizdeki tüm rotaları burada görebilirsiniz ↓',
      pages: 'SAYFALAR',
      homepage: 'Ana sayfa',
    },
  },
  ru: {
    common: {
      appName: 'Language Learning App',
      language: 'Язык',
      home: 'Главная',
      lessons: 'Уроки',
      practice: 'Практика',
      progress: 'Прогресс',
      available: 'Доступно',
      privacyPolicy: 'Политика конфиденциальности',
      contactSupport: 'Связаться с поддержкой',
      allRightsReserved: 'Все права защищены.',
      live: 'Онлайн',
      connected: 'Подключено',
      enabled: 'Включено',
      locked: 'Недоступно',
      unavailable: 'Недоступно',
      free: 'Бесплатно',
      loaderUnavailable: 'Данные загрузчика временно недоступны в этом потоке рендера.',
      wordFallback: 'Слово {id}',
      languageSaved: 'Язык интерфейса сохранен.',
    },
    shell: {
      title: 'Изучайте азербайджанский по структурированному маршруту',
      subtitle: 'Управляйте страницами уроков, практики и прогресса на выбранном языке интерфейса.',
      switcherLabel: 'Язык интерфейса',
    },
    errors: {
      appErrorDetected: 'Обнаружена ошибка приложения',
      appErrorDescription: 'При работе с приложением произошла ошибка.',
      tryToFix: 'Попробовать исправить',
      showLogs: 'Показать логи',
      copyError: 'Скопировать ошибку',
    },
    home: {
      metaTitle: 'Изучайте азербайджанский онлайн',
      metaDescription: 'Платформа азербайджанского языка с маршрутами CEFR, AI-практикой и гибкими планами.',
      badge: 'Платформа изучения азербайджанского языка',
      title: 'Изучайте азербайджанский по маршруту, который ощущается как реальный продукт, а не пустая страница.',
      subtitle: 'Главная страница теперь читает существующие API уроков, цен и покупок, чтобы опыт ученика отражал реальные данные из репозитория.',
      browseLessons: 'Открыть уроки',
      startPractice: 'Начать практику',
      viewProgress: 'Открыть прогресс',
      lessonLibrary: 'Библиотека уроков',
      lessonLibrarySummary: 'Через /api/lessons доступны {bandCount} диапазонов CEFR и {lessonCount} записей уроков.',
      livePricing: 'Живое ценообразование',
      livePricingSummary: '{planCount} уровней подписки загружаются из /api/pricing?action=plans.',
      practiceSurfaces: 'Поверхности практики',
      practiceSurfacesSummary: 'Spaced repetition и прогресс теперь имеют отдельные маршруты ученика на существующих API.',
      addOnCatalog: 'Каталог дополнений',
      addOnCatalogSummary: '{categoryCount} категории покупок загружаются из /api/purchases?action=available.',
      learningSnapshot: 'Снимок обучения',
      weeklyRhythm: 'Недельный ритм',
      lessonApiStatus: 'Статус API уроков',
      needsDatabase: 'Нужна база данных',
      lessonStatusSummary: 'Данные уроков доступны для страниц ученика и сводок на главной.',
      lessonsLabel: 'Уроки',
      plansLabel: 'Планы',
      catalogsLabel: 'Каталоги',
      lessonsSectionTitle: 'Реальные диапазоны уроков из API',
      lessonsSectionDescription: 'Страницы уроков теперь работают от /api/lessons. Если база не настроена, интерфейс показывает это напрямую.',
      unavailableLevel: 'Недоступно',
      lessonCount: '{count} уроков',
      configureDatabase: 'Настройте DATABASE_URL, чтобы загрузить записи учебного контента.',
      groupedByLevel: 'Данные получены из живого endpoint уроков и сгруппированы по уровням.',
      plansSectionTitle: 'Тарифы для разной глубины обучения',
      curriculumSummary: '{range} учебный план, {exercises} упражнений, {sessions} живых сессий с преподавателем.',
      pricingDetailsLoaded: 'Детали тарифа загружены из API цен.',
      pricingUnavailableTitle: 'Тарифные планы недоступны',
      pricingUnavailableDescription: 'Главная страница не смогла собрать локальный каталог тарифов.',
      catalogSectionTitle: 'Реальные дополнения из purchases API',
      catalogSectionDescription: 'Покупаемые дополнения показываются прямо из существующих API-ответов.',
      catalogUnavailableTitle: 'Данные каталога недоступны',
      catalogUnavailableDescription: 'Главная страница не смогла собрать локальный каталог покупок.',
    },
    lessonsPage: {
      metaTitle: 'Уроки',
      metaDescription: 'Просматривайте записи уроков из API контента азербайджанского языка.',
      eyebrow: 'Уроки',
      title: 'Реальный учебный контент',
      subtitle: 'Этот маршрут напрямую читает /api/lessons и группирует результаты по диапазонам CEFR.',
      dataUnavailable: 'Данные уроков недоступны',
      noLessonRecords: 'Записей уроков пока нет',
      noLessonRecordsDescription: 'Маршрут подключен к реальному API уроков, но сейчас не получает ни одной строки.',
      navigation: 'Навигация',
      practiceQueue: 'Очередь практики',
      progressOverview: 'Обзор прогресса',
      accessTiers: 'Уровни доступа',
      levelLabel: 'Уровень {level}',
      minutesLabel: '{minutes} мин',
      curriculumAccess: 'Доступ к программе {range}',
      curriculumVaries: 'Доступ к программе зависит от плана.',
    },
    practicePage: {
      metaTitle: 'Практика',
      metaDescription: 'Повторяйте элементы spaced repetition и тренируйтесь с живыми API ученика.',
      eyebrow: 'Практика',
      title: 'Очередь spaced repetition',
      subtitle: 'Эта страница использует /api/user и /api/spaced-repetition, а демо-ученик хранится по адресу {email}.',
      updateFailed: 'Не удалось обновить элемент повторения.',
      dataUnavailable: 'Данные практики недоступны',
      learner: 'Ученик',
      dueNow: 'Нужно сейчас',
      status: 'Статус',
      ready: 'Готово',
      cleared: 'Пусто',
      reviewDue: 'Пора повторять',
      translationUnavailable: 'Перевод недоступен',
      interval: 'Интервал {days}д',
      repetitions: 'Повторы {count}',
      ease: 'Сложность {value}',
      again: 'Снова',
      hard: 'Трудно',
      good: 'Хорошо',
      easy: 'Легко',
      noItemsDue: 'Нет элементов для практики',
      noItemsDueDescription: 'Живой endpoint spaced repetition не вернул элементы к повторению. Это может означать, что очередь пуста или набор данных ученика еще недоступен.',
      aiTutorPacks: 'Пакеты кредитов AI-наставника',
      goToProgress: 'К прогрессу',
      packLabel: 'Пакет {key}',
    },
    progressPage: {
      metaTitle: 'Прогресс',
      metaDescription: 'Отслеживайте профиль ученика, доступы и рекомендации по апгрейду.',
      eyebrow: 'Прогресс',
      title: 'Профиль ученика и доступ',
      subtitle: 'Этот маршрут читает /api/user, /api/subscriptions и endpoint рекомендаций по тарифам.',
      dataUnavailable: 'Часть данных прогресса недоступна',
      cefrLevel: 'Уровень CEFR',
      xp: 'XP',
      streak: 'Серия',
      plan: 'План',
      currentEntitlements: 'Текущие права',
      accessLevel: 'Уровень доступа',
      offlineMode: 'Офлайн режим',
      aiPersonalization: 'AI-персонализация',
      speechRecognition: 'Распознавание речи',
      storage: 'Хранилище',
      aiCredits: 'AI-кредиты',
      upgradeRecommendations: 'Рекомендации по апгрейду',
      practiceQueue: 'Очередь практики',
      upgradeTo: 'Перейти на план {plan}',
      noRecommendations: 'Живые записи рекомендаций не были возвращены. Обычно это значит, что профиль ученика отсутствует или пока недостаточно данных использования.',
      availablePlans: 'Доступные планы',
      openLessons: 'Открыть уроки',
      curriculumAccess: 'Доступ к программе {range}',
      livePlanMetadata: 'Живые данные о плане приходят из API цен.',
      storageAmount: '{amount} MB',
    },
    notFound: {
      back: 'Назад',
      title: 'Эта страница пока не существует.',
      subtitle: '"/{path}" пока нет в вашем проекте. Но у вас есть варианты.',
      buildFromScratch: 'Создать с нуля',
      createPageDescription: 'Создать новую страницу по адресу "/{path}"',
      createPage: 'Создать страницу',
      routesHint: 'Все маршруты вашего проекта показаны здесь ↓',
      pages: 'СТРАНИЦЫ',
      homepage: 'Главная',
    },
  },
};

function interpolate(template, values = {}) {
  return template.replace(/\{(.*?)\}/g, (_, key) => {
    const value = values[key.trim()];
    return value === undefined || value === null ? '' : String(value);
  });
}

export function isSupportedLanguage(value) {
  return LANGUAGE_CODES.has(value);
}

export function normalizeLanguage(value) {
  if (typeof value !== 'string' || value.length === 0) {
    return DEFAULT_LANGUAGE;
  }

  const normalized = value.toLowerCase().split('-')[0];
  return isSupportedLanguage(normalized) ? normalized : DEFAULT_LANGUAGE;
}

export function getTranslation(language, key, values) {
  const normalizedLanguage = normalizeLanguage(language);
  const segments = key.split('.');

  let currentValue = translations[normalizedLanguage];
  for (const segment of segments) {
    currentValue = currentValue?.[segment];
  }

  if (typeof currentValue !== 'string') {
    currentValue = translations[DEFAULT_LANGUAGE];
    for (const segment of segments) {
      currentValue = currentValue?.[segment];
    }
  }

  if (typeof currentValue !== 'string') {
    return key;
  }

  return interpolate(currentValue, values);
}
