export const purchaseCatalog = {
  certification_prep: {
    name: 'Certification Exam Prep',
    description: 'Comprehensive preparation for official Azerbaijani language certification exams',
    items: {
      A2: {
        name: 'A2 Certification Prep',
        price: 29.99,
        currency: 'USD',
        description: 'Complete A2 level exam preparation with practice tests and mock exams',
        features: [
          '10 practice exams',
          '500+ practice questions',
          'Speaking test simulator',
          'Writing task evaluator',
          'Progress tracking',
          'Exam strategies guide',
        ],
        validity: '6 months',
        level: 'A2',
      },
      B1: {
        name: 'B1 Certification Prep',
        price: 49.99,
        currency: 'USD',
        description: 'Comprehensive B1 level exam preparation with advanced practice materials',
        features: [
          '15 practice exams',
          '1000+ practice questions',
          'Advanced speaking simulator',
          'Writing portfolio evaluation',
          'Grammar mastery modules',
          'Cultural context materials',
        ],
        validity: '6 months',
        level: 'B1',
      },
      C1: {
        name: 'C1 Certification Prep',
        price: 79.99,
        currency: 'USD',
        description: 'Professional-level C1 exam preparation with expert guidance',
        features: [
          '20 practice exams',
          '2000+ practice questions',
          'Professional speaking scenarios',
          'Academic writing workshop',
          'Literature analysis',
          'Industry-specific vocabulary',
        ],
        validity: '12 months',
        level: 'C1',
      },
    },
  },
  specialized_modules: {
    name: 'Specialized Modules',
    description: 'Domain-specific Azerbaijani language courses for professional and academic use',
    items: {
      business: {
        name: 'Business Azerbaijani',
        price: 39.99,
        currency: 'USD',
        description: 'Professional Azerbaijani for business communication and negotiations',
        features: [
          'Business correspondence',
          'Meeting and negotiation language',
          'Financial terminology',
          'Marketing vocabulary',
          'Case studies and role-plays',
          'Cultural business etiquette',
        ],
        validity: 'lifetime',
        level: 'B1-C1',
      },
      academic: {
        name: 'Academic Writing',
        price: 34.99,
        currency: 'USD',
        description: 'Academic Azerbaijani writing skills for research and publications',
        features: [
          'Research paper structure',
          'Citation styles',
          'Academic vocabulary',
          'Thesis writing guide',
          'Peer review practice',
          'Conference presentation skills',
        ],
        validity: 'lifetime',
        level: 'B2-C2',
      },
      medical: {
        name: 'Medical Azerbaijani',
        price: 44.99,
        currency: 'USD',
        description: 'Medical terminology and patient communication in Azerbaijani',
        features: [
          'Medical terminology',
          'Patient communication',
          'Clinical case studies',
          'Medical documentation',
          'Emergency situations',
          'Healthcare system overview',
        ],
        validity: 'lifetime',
        level: 'B1-C1',
      },
      legal: {
        name: 'Legal Azerbaijani',
        price: 49.99,
        currency: 'USD',
        description: 'Legal terminology and document drafting in Azerbaijani',
        features: [
          'Legal terminology',
          'Contract drafting',
          'Court proceedings',
          'Legal correspondence',
          'Case law analysis',
          'Regulatory compliance',
        ],
        validity: 'lifetime',
        level: 'B2-C2',
      },
    },
  },
  offline_packs: {
    name: 'Offline Content Packs',
    description: 'Downloadable content for offline learning without internet connection',
    items: {
      basic: {
        name: 'Basic Offline Pack',
        price: 19.99,
        currency: 'USD',
        description: 'Essential A1-A2 content for offline learning',
        features: [
          '50 lessons downloadable',
          '1000 vocabulary flashcards',
          'Basic grammar exercises',
          'Audio recordings',
          'Progress sync when online',
        ],
        storage: '500 MB',
        validity: 'lifetime',
        levels: ['A1', 'A2'],
      },
      premium: {
        name: 'Premium Offline Pack',
        price: 39.99,
        currency: 'USD',
        description: 'Comprehensive A1-C2 content for complete offline learning',
        features: [
          '200 lessons downloadable',
          '5000 vocabulary flashcards',
          'Advanced grammar exercises',
          'Video lessons and audio',
          'Offline progress tracking',
          'Regular content updates',
        ],
        storage: '2 GB',
        validity: 'lifetime',
        levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
      },
    },
  },
  ai_credits: {
    name: 'AI Tutor Credits',
    description: 'Personalized AI tutoring sessions for accelerated learning',
    items: {
      10: {
        name: '10 AI Tutor Credits',
        price: 4.99,
        currency: 'USD',
        description: '10 sessions with AI tutor for personalized practice',
        features: [
          '10 one-on-one AI sessions',
          'Personalized feedback',
          'Pronunciation coaching',
          'Grammar correction',
          'Conversation practice',
        ],
        credits: 10,
        validity: '6 months',
      },
      25: {
        name: '25 AI Tutor Credits',
        price: 9.99,
        currency: 'USD',
        description: '25 sessions with AI tutor - best value for regular practice',
        features: [
          '25 one-on-one AI sessions',
          'Priority response time',
          'Advanced feedback',
          'Cultural context explanations',
          'Custom learning path',
        ],
        credits: 25,
        validity: '6 months',
      },
      50: {
        name: '50 AI Tutor Credits',
        price: 17.99,
        currency: 'USD',
        description: '50 sessions with AI tutor for intensive learning',
        features: [
          '50 one-on-one AI sessions',
          '24/7 availability',
          'Premium feedback quality',
          'Specialized topic coaching',
          'Progress optimization',
        ],
        credits: 50,
        validity: '12 months',
      },
    },
  },
  gamified_boosts: {
    name: 'Gamified Boosts',
    description: 'Enhance your learning experience with game-like features and rewards',
    items: {
      streak_protection: {
        name: 'Streak Protection',
        price: 2.99,
        currency: 'USD',
        description: 'Protect your learning streak for 30 days',
        features: [
          '30-day streak protection',
          'Automatic streak recovery',
          'Bonus streak days',
          'Streak celebration rewards',
        ],
        validity: '30 days',
      },
      bonus_quizzes: {
        name: 'Bonus Quiz Pack',
        price: 4.99,
        currency: 'USD',
        description: '50 additional quizzes with instant feedback',
        features: [
          '50 bonus quizzes',
          'Instant feedback',
          'Difficulty adaptation',
          'Progress tracking',
        ],
        validity: 'lifetime',
      },
      xp_boost: {
        name: 'XP Boost',
        price: 3.99,
        currency: 'USD',
        description: 'Double XP for 7 days',
        features: [
          '2x XP multiplier',
          'Level-up bonuses',
          'Achievement acceleration',
          'Leaderboard boost',
        ],
        validity: '7 days',
      },
    },
  },
};

export function getAvailablePurchasesCatalog() {
  return purchaseCatalog;
}