export const cultureCategories = [
  {
    id: 'crafts',
    emoji: '🧶',
    title: {
      az: 'Ənənəvi sənətlər',
      en: 'Traditional Crafts',
      es: 'Artes tradicionales',
      ru: 'Традиционные ремесла',
      tr: 'Geleneksel el sanatlari',
    },
    description: {
      az: 'Xalca, kəlağayı, misgərlik və şəbəkə kimi sənətlər milli yaddaşı yaşadır.',
      en: 'Carpet weaving, kelaghayi silk, copperwork, and shabaka keep heritage alive.',
      es: 'El tejido de alfombras, la seda kelaghayi, el cobre y la shabaka mantienen vivo el patrimonio.',
      ru: 'Ковроткачество, келагаи, медное ремесло и шебеке сохраняют культурное наследие.',
      tr: 'Hali dokumaciligi, kelagayi ipegi, bakir isçiligi ve sebeke sanati mirasi yasatir.',
    },
    entries: [
      {
        id: 'kelaghayi',
        type: 'craft',
        title: {
          az: 'Kəlağayı',
          en: 'Kelaghayi Silk Scarves',
          es: 'Panuelos de seda Kelaghayi',
          ru: 'Шелковые платки келагаи',
          tr: 'Kelagayi ipek esarplari',
        },
        period: {
          az: 'Şəki, Başqal və Gəncə ənənələri',
          en: 'Traditions from Sheki, Basgal, and Ganja',
          es: 'Tradiciones de Sheki, Basgal y Ganja',
          ru: 'Традиции Шеки, Басгала и Гянджи',
          tr: 'Seki, Basgal ve Gence gelenekleri',
        },
        blurb: {
          az: 'Kəlağayı qadın geyimindən çox, rəng və naxış dili ilə status, zəriflik və bayram ovqatı daşıyır.',
          en: 'Kelaghayi is more than clothing; its colors and patterns communicate elegance, status, and celebration.',
          es: 'Kelaghayi es mas que una prenda; sus colores y patrones expresan elegancia, estatus y celebracion.',
          ru: 'Келагаи - это больше, чем одежда: его цвета и узоры передают изящество, статус и праздничное настроение.',
          tr: 'Kelagayi bir kiyafetten fazlasidir; renkleri ve desenleri zarafet, statü ve kutlama hissi tasir.',
        },
        takeaways: [
          {
            az: 'İpək parca taxta qəliblərlə boyanır və hər motivin ayrıca simvolik mənası var.',
            en: 'Silk is dyed with carved wooden stamps, and each motif has symbolic meaning.',
            es: 'La seda se tinta con sellos de madera tallada y cada motivo tiene un significado simbolico.',
            ru: 'Шелк окрашивают резными деревянными штампами, и каждый орнамент имеет символическое значение.',
            tr: 'Ipek, oyma ahsap kaliplarla boyanir ve her motifin sembolik bir anlami vardir.',
          },
          {
            az: 'UNESCO siyahısına daxil edilən bu sənət toy və bayram mədəniyyəti ilə sıx bağlıdır.',
            en: 'Recognized by UNESCO, the craft is closely tied to weddings and festive rituals.',
            es: 'Reconocido por la UNESCO, este arte esta estrechamente vinculado a bodas y rituales festivos.',
            ru: 'Это ремесло признано ЮНЕСКО и тесно связано со свадебными и праздничными обрядами.',
            tr: 'UNESCO tarafindan taninan bu sanat, dügünler ve kutlama ritüelleriyle yakindan iliskilidir.',
          },
        ],
      },
      {
        id: 'carpet-weaving',
        type: 'craft',
        title: {
          az: 'Azərbaycan xalca məktəbləri',
          en: 'Azerbaijani Carpet Schools',
          es: 'Escuelas de alfombras de Azerbaiyan',
          ru: 'Азербайджанские школы ковроткачества',
          tr: 'Azerbaycan hali ekolleri',
        },
        period: {
          az: 'Qarabağ, Quba, Şirvan, Təbriz',
          en: 'Karabakh, Guba, Shirvan, and Tabriz',
          es: 'Karabaj, Guba, Shirvan y Tabriz',
          ru: 'Карабах, Губа, Ширван и Тебриз',
          tr: 'Karabag, Kuba, Sirvan ve Tebriz',
        },
        blurb: {
          az: 'Xalca yalnız məişət eşyası deyil; bölgələrin rəng ritmi, heyvan motivləri və simvolik dilidir.',
          en: 'Carpets are not just household objects; they encode regional color systems, animal motifs, and symbolic language.',
          es: 'Las alfombras no son solo objetos domesticos; contienen sistemas regionales de color, motivos animales y lenguaje simbolico.',
          ru: 'Ковры - это не просто предметы быта, а система региональных цветов, животных мотивов и символического языка.',
          tr: 'Halilar sadece ev esyasi degildir; bölgesel renk sistemleri, hayvan motifleri ve sembolik dili tasir.',
        },
        takeaways: [
          {
            az: 'Qarabağ xalcalarında iri gül kompozisiyaları, Quba məktəbində isə daha incə həndəsi ritm görünür.',
            en: 'Karabakh carpets favor bold floral compositions, while Guba pieces often emphasize fine geometry.',
            es: 'Las alfombras de Karabaj prefieren composiciones florales fuertes, mientras que las de Guba destacan una geometria mas fina.',
            ru: 'Карабахские ковры тяготеют к крупным цветочным композициям, а губинские - к тонкой геометрии.',
            tr: 'Karabag halilari belirgin cicek kompozisyonlarini, Kuba halilari ise ince geometrik ritmi öne cikarir.',
          },
          {
            az: 'Xalca motivləri dil öyrənənlər üçün rəng, forma və təbiət leksikasını təbii yolla açır.',
            en: 'Carpet motifs give learners a natural entry into vocabulary about color, shape, and nature.',
            es: 'Los motivos de las alfombras ofrecen una entrada natural al vocabulario de colores, formas y naturaleza.',
            ru: 'Ковровые узоры помогают естественно освоить лексику о цвете, форме и природе.',
            tr: 'Hali motifleri, renk, sekil ve doga kelime dagarcigina dogal bir giris saglar.',
          },
        ],
      },
    ],
  },
  {
    id: 'poetry',
    emoji: '📜',
    title: {
      az: 'Şeir və ədəbiyyat',
      en: 'Poetry and Literature',
      es: 'Poesia y literatura',
      ru: 'Поэзия и литература',
      tr: 'Siir ve edebiyat',
    },
    description: {
      az: 'Nizami, Füzuli, Natəvan və aşıq ənənəsi dilin emosional qatını açır.',
      en: 'Nizami, Fuzuli, Natavan, and the ashig tradition reveal the emotional depth of the language.',
      es: 'Nizami, Fuzuli, Natavan y la tradicion ashig revelan la profundidad emocional del idioma.',
      ru: 'Низами, Физули, Натаван и традиция ашугов раскрывают эмоциональную глубину языка.',
      tr: 'Nizami, Fuzuli, Natavan ve asik gelenegi dilin duygusal derinligini gösterir.',
    },
    entries: [
      {
        id: 'nizami',
        type: 'poet',
        title: {
          az: 'Nizami Gəncəvi',
          en: 'Nizami Ganjavi',
          es: 'Nizami Ganjavi',
          ru: 'Низами Гянджеви',
          tr: 'Nizami Gencevi',
        },
        period: {
          az: '1141-1209',
          en: '1141-1209',
          es: '1141-1209',
          ru: '1141-1209',
          tr: '1141-1209',
        },
        blurb: {
          az: 'Nizaminin əsərləri sevgi, ədalət və hikmət mövzularını poetik hekayə ilə birləşdirir.',
          en: 'Nizami combines love, justice, and wisdom with narrative poetry of remarkable precision.',
          es: 'Nizami combina amor, justicia y sabiduria con una poesia narrativa de gran precision.',
          ru: 'Низами соединяет любовь, справедливость и мудрость с удивительно точной повествовательной поэзией.',
          tr: 'Nizami, ask, adalet ve bilgeligi son derece incelikli anlatimci siirle birlestirir.',
        },
        takeaways: [
          {
            az: 'Xəmsə silsiləsi Azərbaycan mədəni təsəvvüründə etik və estetik meyar kimi yaşayır.',
            en: 'The Khamsa remains a benchmark for ethics and beauty in Azerbaijani cultural memory.',
            es: 'La Jamsa sigue siendo una referencia de etica y belleza en la memoria cultural azerbaiyana.',
            ru: 'Хамса остается эталоном этики и красоты в культурной памяти Азербайджана.',
            tr: 'Hamse, Azerbaycan kültürel hafizasinda etik ve estetik bir ölçü olmaya devam eder.',
          },
          {
            az: 'Şeir modulu vasitəsilə metafora, sevgi leksikası və klassik üslub öyrənilə bilər.',
            en: 'A poetry module can teach metaphor, the language of love, and classical style.',
            es: 'Un modulo de poesia puede ensenar metafora, lenguaje del amor y estilo clasico.',
            ru: 'Через поэзию можно изучать метафору, лексику любви и классический стиль.',
            tr: 'Bir siir modülü metafor, ask dili ve klasik üslubu ögretebilir.',
          },
        ],
      },
      {
        id: 'ashig-tradition',
        type: 'poet',
        title: {
          az: 'Aşıq sənəti',
          en: 'The Ashig Tradition',
          es: 'La tradicion Ashig',
          ru: 'Традиция ашугов',
          tr: 'Asik gelenegi',
        },
        period: {
          az: 'Şifahi poeziya və saz musiqisi',
          en: 'Oral poetry and saz performance',
          es: 'Poesia oral y actuacion con saz',
          ru: 'Устная поэзия и исполнение под саз',
          tr: 'Sözlü siir ve saz icrasi',
        },
        blurb: {
          az: 'Aşıqlar improvizasiya, hekayəçilik və musiqini bir səhnədə birləşdirərək dili canlı saxlayır.',
          en: 'Ashigs keep the language alive by joining improvisation, storytelling, and music in one performance.',
          es: 'Los ashig mantienen vivo el idioma uniendo improvisacion, narracion y musica en una sola actuacion.',
          ru: 'Ашуги поддерживают язык живым, соединяя импровизацию, рассказ и музыку в одном выступлении.',
          tr: 'Asiklar dili, dogaclama, hikaye anlatimi ve müzigi tek bir performansta birlestirerek yasatir.',
        },
        takeaways: [
          {
            az: 'Bu janr dialoq, sual-cavab və ritmik təkrarlar üçün ideal dinləmə materialıdır.',
            en: 'This genre is ideal for listening practice with dialogue, call-and-response, and rhythm.',
            es: 'Este genero es ideal para practicar comprension con dialogo, respuesta y ritmo.',
            ru: 'Этот жанр отлично подходит для аудирования с диалогом, перекличкой и ритмом.',
            tr: 'Bu tür, diyalog, soru-cevap ve ritimle dinleme calismasi icin idealdir.',
          },
          {
            az: 'Aşıq ədəbiyyatı dil öyrənənlərə məcaz və mədəni yaddaşın necə işlədiyini göstərir.',
            en: 'Ashig poetry shows learners how metaphor and collective memory work together.',
            es: 'La poesia ashig muestra como funcionan juntos la metafora y la memoria colectiva.',
            ru: 'Поэзия ашугов показывает, как вместе работают метафора и коллективная память.',
            tr: 'Asik siiri, metaforla kolektif hafizanin nasil birlikte isledigini gösterir.',
          },
        ],
      },
    ],
  },
  {
    id: 'holidays',
    emoji: '🎉',
    title: {
      az: 'Milli bayramlar',
      en: 'National Holidays',
      es: 'Fiestas nacionales',
      ru: 'Национальные праздники',
      tr: 'Ulusal bayramlar',
    },
    description: {
      az: 'Novruzdan Müstəqillik Gününə qədər bayramlar ailə, yaddaş və mərasim dili yaradır.',
      en: 'From Novruz to Independence Day, holidays shape family rituals, memory, and seasonal language.',
      es: 'Desde Novruz hasta el Dia de la Independencia, las fiestas forman rituales familiares, memoria y lenguaje estacional.',
      ru: 'От Новруза до Дня независимости праздники формируют семейные ритуалы, память и сезонную лексику.',
      tr: 'Nevruzdan Bagimsizlik Gününe kadar bayramlar aile ritüellerini, hafizayi ve mevsimsel dili sekillendirir.',
    },
    entries: [
      {
        id: 'novruz',
        type: 'holiday',
        title: {
          az: 'Novruz',
          en: 'Novruz',
          es: 'Novruz',
          ru: 'Новруз',
          tr: 'Nevruz',
        },
        period: {
          az: 'Yaz bərabərliyi və dörd çərşənbə',
          en: 'Spring equinox and the four Tuesdays',
          es: 'Equinoccio de primavera y los cuatro martes',
          ru: 'Весеннее равноденствие и четыре вторника',
          tr: 'Ilkbahar ekinoksu ve dört carsamba onceki salilar',
        },
        blurb: {
          az: 'Novruz təbiətin oyanısını ailə süfrəsi, tonqal, səməni və qonaqlıqlar vasitəsilə qeyd edir.',
          en: 'Novruz celebrates renewal through bonfires, samani sprouts, family tables, and neighborly visits.',
          es: 'Novruz celebra la renovacion con hogueras, brotes de samani, mesas familiares y visitas a vecinos.',
          ru: 'Новруз отмечает обновление через костры, сэмэни, семейный стол и визиты к соседям.',
          tr: 'Nevruz, atesler, semeni filizleri, aile sofralari ve komsu ziyaretleriyle yenilenmeyi kutlar.',
        },
        takeaways: [
          {
            az: 'Bayram leksikası uçun yumurta döyüşdürmək, səməni, şirniyyat və tonqal kimi sözlər əsasdır.',
            en: 'Key vocabulary includes egg tapping, samani, sweets, bonfires, and holiday greetings.',
            es: 'El vocabulario clave incluye choque de huevos, samani, dulces, hogueras y saludos festivos.',
            ru: 'Ключевая лексика включает битву яйцами, сэмэни, сладости, костры и праздничные поздравления.',
            tr: 'Temel kelimeler yumurta tokuşturma, semeni, tatlilar, atesler ve bayram selamlaridir.',
          },
          {
            az: 'Hər çərşənbə su, od, yel və torpaq elementləri ilə bağlı ayrıca mədəni qat daşıyır.',
            en: 'Each pre-holiday Tuesday highlights water, fire, wind, and earth as symbolic elements.',
            es: 'Cada martes previo a la fiesta destaca agua, fuego, viento y tierra como elementos simbolicos.',
            ru: 'Каждый предпраздничный вторник подчеркивает воду, огонь, ветер и землю как символы.',
            tr: 'Bayram öncesi her sali, su, ates, rüzgar ve toprak unsurlarini vurgular.',
          },
        ],
      },
      {
        id: 'independence-day',
        type: 'holiday',
        title: {
          az: 'Müstəqillik Günü',
          en: 'Independence Day',
          es: 'Dia de la Independencia',
          ru: 'День независимости',
          tr: 'Bagimsizlik Günü',
        },
        period: {
          az: '28 May',
          en: 'May 28',
          es: '28 de mayo',
          ru: '28 мая',
          tr: '28 Mayis',
        },
        blurb: {
          az: '1918-ci ildə qurulan Azərbaycan Xalq Cümhuriyyəti müasir dövlətçilik dilinin əsas istinad nöqtəsidir.',
          en: 'The 1918 Azerbaijan Democratic Republic remains a key reference point for modern civic language.',
          es: 'La Republica Democratica de Azerbaiyan de 1918 sigue siendo una referencia central para el lenguaje civico moderno.',
          ru: 'Азербайджанская Демократическая Республика 1918 года остается важной точкой отсчета для современного гражданского языка.',
          tr: '1918 Azerbaycan Demokratik Cumhuriyeti, modern yurttaslik dilinin temel referanslarindan biridir.',
        },
        takeaways: [
          {
            az: 'Bu mövzu dövlət atributları, tarix və ictimai nitq leksikasını öyrətmək üçün əlverislidir.',
            en: 'This topic is useful for teaching state symbols, history, and public-speech vocabulary.',
            es: 'Este tema sirve para ensenar simbolos del Estado, historia y vocabulario de discurso publico.',
            ru: 'Эта тема полезна для изучения государственной символики, истории и лексики публичной речи.',
            tr: 'Bu konu, devlet sembolleri, tarih ve kamusal konusma kelime dagarcigini ögretmek icin uygundur.',
          },
          {
            az: 'Mətnlərdə “cümhuriyyət”, “müstəqillik” və “suverenlik” kimi anlayışlar önə çıxır.',
            en: 'Texts often foreground concepts such as republic, independence, and sovereignty.',
            es: 'Los textos suelen destacar conceptos como republica, independencia y soberania.',
            ru: 'В текстах часто выделяются понятия республика, независимость и суверенитет.',
            tr: 'Metinlerde cumhuriyet, bagimsizlik ve egemenlik gibi kavramlar öne cikar.',
          },
        ],
      },
    ],
  },
  {
    id: 'regions',
    emoji: '🏛️',
    title: {
      az: 'Bölgələr və memarlıq',
      en: 'Regions and Architecture',
      es: 'Regiones y arquitectura',
      ru: 'Регионы и архитектура',
      tr: 'Bölgeler ve mimari',
    },
    description: {
      az: 'Şəki, Bakı və Qobustan kimi məkanlar tarix, sənət və coğrafiyanı birləşdirir.',
      en: 'Places like Sheki, Baku, and Gobustan connect history, art, and geography.',
      es: 'Lugares como Sheki, Baku y Gobustan conectan historia, arte y geografia.',
      ru: 'Такие места, как Шеки, Баку и Гобустан, соединяют историю, искусство и географию.',
      tr: 'Seki, Bakü ve Gobustan gibi yerler tarih, sanat ve cografyayi birlestirir.',
    },
    entries: [
      {
        id: 'sheki-palace',
        type: 'region',
        title: {
          az: 'Şəki xan sarayı',
          en: 'Sheki Khan’s Palace',
          es: 'Palacio del Khan de Sheki',
          ru: 'Дворец шекинских ханов',
          tr: 'Seki Han Sarayi',
        },
        period: {
          az: '18-ci əsr',
          en: '18th century',
          es: 'Siglo XVIII',
          ru: 'XVIII век',
          tr: '18. yüzyil',
        },
        blurb: {
          az: 'Şəbəkə pəncərələri və divar rəsmləri ilə saray Azərbaycan dekorativ zövqünün zirvəsini göstərir.',
          en: 'Its shabaka windows and murals showcase the height of Azerbaijani decorative taste.',
          es: 'Sus ventanas shabaka y murales muestran la cima del gusto decorativo azerbaiyano.',
          ru: 'Витражи шебеке и настенные росписи демонстрируют вершину азербайджанского декоративного вкуса.',
          tr: 'Sebeke pencereleri ve duvar resimleri, Azerbaycan süsleme zevkinin zirvesini gösterir.',
        },
        takeaways: [
          {
            az: 'Memarlıq modulu pəncərə, naxış, rəng və sarayla bağlı təsviri leksikanı gücləndirə bilər.',
            en: 'An architecture module can reinforce descriptive vocabulary about windows, patterns, color, and palaces.',
            es: 'Un modulo de arquitectura puede reforzar vocabulario descriptivo sobre ventanas, patrones, color y palacios.',
            ru: 'Архитектурный модуль может укрепить описательную лексику о окнах, орнаментах, цвете и дворцах.',
            tr: 'Bir mimari modülü pencere, desen, renk ve saraylarla ilgili betimleyici kelime dagarcigini güçlendirebilir.',
          },
          {
            az: 'Şəki həm də ipək yolunun ticarət və sənət əlaqələri ilə tanınır.',
            en: 'Sheki is also known for Silk Road trade links and artisan networks.',
            es: 'Sheki tambien es conocida por sus conexiones comerciales de la Ruta de la Seda y sus redes artesanales.',
            ru: 'Шеки также известен связями Шелкового пути и ремесленными сетями.',
            tr: 'Seki, Ipek Yolu ticaret baglantilari ve zanaat aglariyla da bilinir.',
          },
        ],
      },
      {
        id: 'gobustan',
        type: 'region',
        title: {
          az: 'Qobustan qayaüstü təsvirləri',
          en: 'Gobustan Rock Art',
          es: 'Arte rupestre de Gobustan',
          ru: 'Наскальное искусство Гобустана',
          tr: 'Gobustan kaya resimleri',
        },
        period: {
          az: 'Qədim məskən və UNESCO irsi',
          en: 'Ancient settlement and UNESCO heritage',
          es: 'Asentamiento antiguo y patrimonio de la UNESCO',
          ru: 'Древнее поселение и наследие ЮНЕСКО',
          tr: 'Antik yerlesim ve UNESCO mirasi',
        },
        blurb: {
          az: 'Qobustan insanın, heyvanın və hərəkətin daşa köçürülmüş vizual tarixidir.',
          en: 'Gobustan is a visual history of humans, animals, and movement carved into stone.',
          es: 'Gobustan es una historia visual de humanos, animales y movimiento tallada en piedra.',
          ru: 'Гобустан - это визуальная история людей, животных и движения, высеченная в камне.',
          tr: 'Gobustan, insanin, hayvanin ve hareketin tasa kazinmis görsel tarihidir.',
        },
        takeaways: [
          {
            az: 'Bu mövzu tarix öncəsi həyat, ov və təsvir felləri ilə bağlı lüğəti genişləndirir.',
            en: 'This topic expands vocabulary around prehistory, hunting, and visual description.',
            es: 'Este tema amplia el vocabulario sobre prehistoria, caza y descripcion visual.',
            ru: 'Эта тема расширяет лексику о доистории, охоте и визуальном описании.',
            tr: 'Bu konu, tarih öncesi yasam, avcilik ve görsel betimleme kelimelerini genisletir.',
          },
          {
            az: 'Öyrənənlər təsvir etmə bacarığını tarix məzmunu ilə birgə məşq edə bilər.',
            en: 'Learners can practice description skills alongside historical content.',
            es: 'Los estudiantes pueden practicar habilidades descriptivas junto con contenido historico.',
            ru: 'Изучающие язык могут тренировать описание вместе с историческим содержанием.',
            tr: 'Ögreniciler, tarihsel icerikle birlikte betimleme becerilerini calisabilir.',
          },
        ],
      },
    ],
  },
  {
    id: 'cinema',
    emoji: '🎬',
    title: {
      az: 'Kino və teatr',
      en: 'Cinema and Theater',
      es: 'Cine y teatro',
      ru: 'Кино и театр',
      tr: 'Sinema ve tiyatro',
    },
    description: {
      az: 'Səhnə və ekran dili müasir Azərbaycan cəmiyyətinin yumorunu, dramını və ritmini göstərir.',
      en: 'Stage and screen language reveal the humor, drama, and rhythm of modern Azerbaijani society.',
      es: 'El lenguaje de escena y pantalla revela el humor, el drama y el ritmo de la sociedad azerbaiyana moderna.',
      ru: 'Язык сцены и экрана показывает юмор, драму и ритм современного азербайджанского общества.',
      tr: 'Sahne ve ekran dili, modern Azerbaycan toplumunun mizahini, dramini ve ritmini gösterir.',
    },
    entries: [
      {
        id: 'uzeyir-hajibeyov',
        type: 'cinema',
        title: {
          az: 'Üzeyir Hacıbəyov',
          en: 'Uzeyir Hajibeyov',
          es: 'Uzeyir Hajibeyov',
          ru: 'Узеир Гаджибейов',
          tr: 'Uzeyir Hacibeyov',
        },
        period: {
          az: 'Opera, teatr və musiqi islahatı',
          en: 'Opera, theater, and musical reform',
          es: 'Opera, teatro y reforma musical',
          ru: 'Опера, театр и музыкальная реформа',
          tr: 'Opera, tiyatro ve müzik reformu',
        },
        blurb: {
          az: '“Leyli və Məcnun” ilə Hacıbəyov Şərqdə operanın yeni mərhələsini açdı.',
          en: 'With Leyli and Majnun, Hajibeyov opened a new chapter for opera in the Muslim East.',
          es: 'Con Leyli y Majnun, Hajibeyov abrio un nuevo capitulo para la opera en el Oriente musulman.',
          ru: 'С оперой «Лейли и Меджнун» Гаджибейов открыл новую главу оперы на мусульманском Востоке.',
          tr: 'Leyli ve Mecnun ile Hacibeyov, Müslüman Doguda opera icin yeni bir dönem acti.',
        },
        takeaways: [
          {
            az: 'Musiqi modulu səhnə, tamaşaçı, librettto və orkestr kimi sözləri təbii şəkildə təqdim edə bilər.',
            en: 'A music module can naturally introduce words like stage, audience, libretto, and orchestra.',
            es: 'Un modulo de musica puede introducir naturalmente palabras como escenario, publico, libreto y orquesta.',
            ru: 'Музыкальный модуль может естественно вводить слова сцена, публика, либретто и оркестр.',
            tr: 'Bir müzik modülü, sahne, seyirci, libretto ve orkestra gibi sözcükleri dogal bicimde tanitabilir.',
          },
          {
            az: 'Sənət və milli kimlik arasındakı əlaqə bu mövzuda güclü şəkildə görünür.',
            en: 'The link between artistic innovation and national identity is especially strong here.',
            es: 'Aqui se ve con fuerza la relacion entre innovacion artistica e identidad nacional.',
            ru: 'Здесь особенно заметна связь между художественным новаторством и национальной идентичностью.',
            tr: 'Sanatsal yenilik ile ulusal kimlik arasindaki bag burada özellikle belirgindir.',
          },
        ],
      },
      {
        id: 'jafar-jabbarli',
        type: 'cinema',
        title: {
          az: 'Cəfər Cabbarlı',
          en: 'Jafar Jabbarli',
          es: 'Jafar Jabbarli',
          ru: 'Джафар Джаббарлы',
          tr: 'Cafer Cabbarli',
        },
        period: {
          az: 'Dramaturgiya və erkən kino',
          en: 'Playwriting and early cinema',
          es: 'Dramaturgia y cine temprano',
          ru: 'Драматургия и раннее кино',
          tr: 'Oyun yazarligi ve erken sinema',
        },
        blurb: {
          az: 'Cabbarlı cəmiyyət, qadın obrazı və modernləşmə mövzularını səhnəyə gətirən əsas adlardandır.',
          en: 'Jabbarli is central to bringing social change, women’s voices, and modernity onto the stage.',
          es: 'Jabbarli fue clave para llevar al escenario el cambio social, las voces femeninas y la modernidad.',
          ru: 'Джаббарлы сыграл важную роль в том, чтобы вывести на сцену социальные перемены, женские голоса и модернизацию.',
          tr: 'Cabbarli, toplumsal degisim, kadin sesleri ve modernligi sahneye tasiyan temel isimlerdendir.',
        },
        takeaways: [
          {
            az: 'Bu bölmə debat, fikir ifadəsi və ictimai mövqeni bildirən dil nümunələri üçün güclü materialdır.',
            en: 'This section supports debate, opinion language, and socially engaged vocabulary.',
            es: 'Esta seccion apoya el debate, el lenguaje de opinion y el vocabulario con compromiso social.',
            ru: 'Этот раздел поддерживает лексику для дискуссий, выражения мнения и социальной позиции.',
            tr: 'Bu bölüm, tartisma, görüs bildirme ve toplumsal duyarlilik dilini destekler.',
          },
          {
            az: 'Teatr və kino öyrənənlərə qeyd olunan dövrün ictimai dəyişikliklərini oxumağa kömək edir.',
            en: 'Theater and film help learners read social transformations of the period.',
            es: 'El teatro y el cine ayudan a leer las transformaciones sociales del periodo.',
            ru: 'Театр и кино помогают увидеть социальные изменения эпохи.',
            tr: 'Tiyatro ve sinema, dönemin toplumsal dönüsümlerini okumaya yardimci olur.',
          },
        ],
      },
    ],
  },
  {
    id: 'etiquette',
    emoji: '☕',
    title: {
      az: 'Müasir həyat və etiket',
      en: 'Modern Life and Etiquette',
      es: 'Vida moderna y etiqueta',
      ru: 'Современная жизнь и этикет',
      tr: 'Modern yasam ve görgü',
    },
    description: {
      az: 'Çay, qonaqpərvərlik, ailə ünsiyyəti və gündəlik nəzakət dili gündəlik praktikaya ən yaxın qatlardır.',
      en: 'Tea, hospitality, family interaction, and everyday politeness are the most practical cultural layers.',
      es: 'El te, la hospitalidad, la interaccion familiar y la cortesia diaria son las capas culturales mas practicas.',
      ru: 'Чай, гостеприимство, семейное общение и повседневная вежливость - самые практичные культурные слои.',
      tr: 'Cay, misafirperverlik, aile iletisimleri ve günlük nezaket en pratik kültürel katmanlardir.',
    },
    entries: [
      {
        id: 'tea-culture',
        type: 'etiquette',
        title: {
          az: 'Çay süfrəsi',
          en: 'Tea Table Culture',
          es: 'Cultura de la mesa de te',
          ru: 'Культура чайного стола',
          tr: 'Cay sofrasi kültürü',
        },
        period: {
          az: 'Gündəlik qonaqpərvərlik ənənəsi',
          en: 'An everyday hospitality ritual',
          es: 'Un ritual cotidiano de hospitalidad',
          ru: 'Ежедневный ритуал гостеприимства',
          tr: 'Günlük bir misafirperverlik ritüeli',
        },
        blurb: {
          az: 'Armudu stəkan, mürəbbə və sakit söhbət Azərbaycan qonaqpərvərliyinin əsas vizual kodlarıdır.',
          en: 'Armudu glasses, jam, and unhurried conversation are signature images of Azerbaijani hospitality.',
          es: 'Los vasos armudu, la mermelada y la conversacion tranquila son imagenes clave de la hospitalidad azerbaiyana.',
          ru: 'Стаканы армуды, варенье и неспешная беседа - знаковые образы азербайджанского гостеприимства.',
          tr: 'Armudu bardaklar, recel ve sakin sohbet, Azerbaycan misafirperverliginin simge görüntüleridir.',
        },
        takeaways: [
          {
            az: 'Bu tema dəvət, təklif, minnətdarlıq və nəzakətli imtina kimi nitq aktlarını işləmək üçün uyğundur.',
            en: 'This theme is perfect for practicing invitations, offers, thanks, and polite refusal.',
            es: 'Este tema es ideal para practicar invitaciones, ofrecimientos, agradecimientos y rechazo cortés.',
            ru: 'Эта тема отлично подходит для тренировки приглашений, предложений, благодарности и вежливого отказа.',
            tr: 'Bu tema, davet, ikram, tesekkür ve nazikçe reddetme kaliplarini calismak icin uygundur.',
          },
          {
            az: 'Gündəlik danışıqda çay ətrafında qurulan söhbət sosial yaxınlığı göstərir.',
            en: 'Conversation around tea often signals warmth and social closeness.',
            es: 'La conversacion en torno al te suele expresar calidez y cercania social.',
            ru: 'Разговор за чаем часто выражает теплоту и социальную близость.',
            tr: 'Cay etrafindaki sohbet, genellikle samimiyet ve toplumsal yakinlik ifade eder.',
          },
        ],
      },
      {
        id: 'guest-etiquette',
        type: 'etiquette',
        title: {
          az: 'Qonaqlıq etiketi',
          en: 'Guest Etiquette',
          es: 'Etiqueta para invitados',
          ru: 'Этикет гостя',
          tr: 'Misafir görgüsü',
        },
        period: {
          az: 'Ailə və qonşuluq münasibətləri',
          en: 'Family and neighborhood relations',
          es: 'Relaciones familiares y vecinales',
          ru: 'Семейные и соседские отношения',
          tr: 'Aile ve komsuluk iliskileri',
        },
        blurb: {
          az: 'Salamlaşma, yer göstərmək, israrla ikram etmək və böyüklərə hörmət gündəlik ünsiyyətin vacib hissəsidir.',
          en: 'Greeting properly, offering a seat, insisting on hospitality, and showing respect to elders matter in everyday interaction.',
          es: 'Saludar bien, ofrecer asiento, insistir en la hospitalidad y mostrar respeto a los mayores importa en la interaccion diaria.',
          ru: 'Правильное приветствие, предложение места, настойчивое угощение и уважение к старшим важны в повседневном общении.',
          tr: 'Dogru selamlama, yer teklif etme, ikramda israr ve büyüklere saygi günlük iletisimin önemli parcalaridir.',
        },
        takeaways: [
          {
            az: 'Etiket modulu “buyurun”, “zəhmət olmasa” və “əliniz dərd görməsin” kimi ifadələri öyrədə bilər.',
            en: 'An etiquette module can teach expressions like buyurun, please, and blessings for the host’s effort.',
            es: 'Un modulo de etiqueta puede ensenar expresiones como buyurun, por favor y bendiciones por el esfuerzo del anfitrion.',
            ru: 'Модуль по этикету может обучать выражениям вроде buyurun, пожалуйста и добрым пожеланиям хозяину.',
            tr: 'Bir görgü modülü, buyurun, lütfen ve ev sahibine hayir duasini ifade eden kaliplari ögretebilir.',
          },
          {
            az: 'Bu mövzu praktik danışıq tapşırıqları və rol oyunu üçün birbasa uyğundur.',
            en: 'This topic fits naturally into speaking drills and role-play.',
            es: 'Este tema encaja de forma natural en ejercicios orales y juegos de rol.',
            ru: 'Эта тема естественно подходит для разговорной практики и ролевых игр.',
            tr: 'Bu konu, konusma alistirmalari ve rol oyunlari icin dogal bir uyum saglar.',
          },
        ],
      },
    ],
  },
];

export function getCultureCategoryById(categoryId) {
  return cultureCategories.find((category) => category.id === categoryId) ?? cultureCategories[0] ?? null;
}